/*
DOOM generic portado para Harbour com interfaces minimas em C para acesso a allegro.

Por Wagner Nunes da Silva

vagucs@bol.com.br
vagucs@vagucs.com.br
vagucs@gmail.com

www.vagucs.com.br
*/
#include "xhb.ch"
#include "common.ch"
#include "hbclass.ch"
#include "fileio.ch"

#translate ( <exp1> | <exp2> )      => ( hb_qbitOr( ( <exp1> ), ( <exp2> ) ) )
#translate ( <exp1> & <exp2> )      => ( hb_qbitAnd( ( <exp1> ), ( <exp2> ) ) )
#translate ( <exp1> ^^ <exp2> )     => ( hb_qbitXor( ( <exp1> ), ( <exp2> ) ) )

#include "gusconf.ch"

#ifndef PU_STATIC
#define PU_STATIC 1
#endif

#define MAX_INSTRUMENTS 256

CLASS gus_config_t
    DATA patch_names
    DATA mapping
    METHOD New()
ENDCLASS

METHOD New() CLASS gus_config_t
    LOCAL i

    ::patch_names := {}
    ::mapping := {}
    FOR i := 1 TO MAX_INSTRUMENTS
        AAdd( ::patch_names, NIL )
        AAdd( ::mapping, -1 )
    NEXT
RETURN Self

INIT PROCEDURE init_gusconf

    PUBLIC gus_patch_path
    PUBLIC gus_ram_kb

    gus_patch_path := ""
    gus_ram_kb := 1024
RETURN

STATIC FUNCTION MappingIndex()
    LOCAL nResult
    MEMVAR gus_ram_kb

    nResult := Int( gus_ram_kb / 256 )
    IF nResult < 1
        RETURN 1
    ENDIF
    IF nResult > 4
        RETURN 4
    ENDIF
RETURN nResult

STATIC FUNCTION SplitLine( cLine, nMax )
    LOCAL aFields
    LOCAL nHash
    LOCAL cWork
    LOCAL aTok
    LOCAL i

    aFields := {}
    cWork := iif( cLine == NIL, "", cLine )
    nHash := At( "#", cWork )
    IF nHash > 0
        cWork := Left( cWork, nHash - 1 )
    ENDIF

    aTok := hb_ATokens( cWork, "," )
    FOR i := 1 TO Len( aTok )
        AAdd( aFields, AllTrim( aTok[ i ] ) )
        IF Len( aFields ) >= nMax
            EXIT
        ENDIF
    NEXT
RETURN aFields

STATIC PROCEDURE ParseLine( oCfg, cLine )
    LOCAL aFields
    LOCAL nInstr
    LOCAL nMapped

    aFields := SplitLine( cLine, 6 )
    IF Len( aFields ) < 6
        RETURN
    ENDIF

    nInstr := Val( aFields[ 1 ] )
    nMapped := Val( aFields[ MappingIndex() + 1 ] )
    IF nInstr < 0 .OR. nInstr >= MAX_INSTRUMENTS
        RETURN
    ENDIF

    oCfg:patch_names[ nInstr + 1 ] := aFields[ 6 ]
    oCfg:mapping[ nInstr + 1 ] := nMapped
RETURN

STATIC PROCEDURE ParseDMXConfig( cDmx, oCfg )
    LOCAL aLines
    LOCAL i

    aLines := hb_ATokens( StrTran( StrTran( cDmx, Chr( 13 ), "" ), Chr( 10 ), Chr( 10 ) ), Chr( 10 ) )
    FOR i := 1 TO Len( aLines )
        ParseLine( oCfg, aLines[ i ] )
    NEXT
RETURN

STATIC FUNCTION ReadDMXConfig()
    LOCAL nLump
    LOCAL nLen
    LOCAL cData

    nLump := W_CheckNumForName( "DMXGUS" )
    IF nLump < 0
        nLump := W_GetNumForName( "DMXGUSC" )
    ENDIF

    nLen := W_LumpLength( nLump )
    cData := Space( nLen )
    W_ReadLump( nLump, @cData )
RETURN cData

STATIC FUNCTION WriteTimidityConfig( cPath, oCfg )
    LOCAL nH
    LOCAL i
    LOCAL nMap
    LOCAL cName
    MEMVAR gus_patch_path

    nH := FCreate( cPath )
    IF nH == F_ERROR
        RETURN .F.
    ENDIF

    FWrite( nH, "# Autogenerated Timidity config." + hb_eol() + hb_eol() )
    FWrite( nH, "dir " + gus_patch_path + hb_eol() )
    FWrite( nH, hb_eol() + "bank 0" + hb_eol() + hb_eol() )

    FOR i := 0 TO 127
        nMap := oCfg:mapping[ i + 1 ]
        IF nMap >= 0 .AND. nMap < MAX_INSTRUMENTS
            cName := oCfg:patch_names[ nMap + 1 ]
            IF cName != NIL
                FWrite( nH, hb_ntos( i ) + " " + cName + hb_eol() )
            ENDIF
        ENDIF
    NEXT

    FWrite( nH, hb_eol() + "drumset 0" + hb_eol() + hb_eol() )

    FOR i := 128 + 25 TO MAX_INSTRUMENTS - 1
        nMap := oCfg:mapping[ i + 1 ]
        IF nMap >= 0 .AND. nMap < MAX_INSTRUMENTS
            cName := oCfg:patch_names[ nMap + 1 ]
            IF cName != NIL
                FWrite( nH, hb_ntos( i - 128 ) + " " + cName + hb_eol() )
            ENDIF
        ENDIF
    NEXT

    FWrite( nH, hb_eol() )
    FClose( nH )
RETURN .T.

FUNCTION GUS_WriteConfig( cPath )
    LOCAL oCfg
    LOCAL cDmx
    LOCAL lOk
    MEMVAR gus_patch_path

    IF Empty( gus_patch_path )
        OutStd( "You haven't configured gus_patch_path." + hb_eol() )
        OutStd( "gus_patch_path needs to point to the location of your GUS patch set." + hb_eol() )
        OutStd( "To get a copy of the " + Chr( 34 ) + "standard" + Chr( 34 ) + ;
            " GUS patches, download a copy of dgguspat.zip." + hb_eol() )
        RETURN .F.
    ENDIF

    oCfg := gus_config_t():New()
    cDmx := ReadDMXConfig()
    ParseDMXConfig( cDmx, oCfg )
    lOk := WriteTimidityConfig( cPath, oCfg )
RETURN lOk
